### ISSUE TITLE
не могу исправить ошибку при запуске ./gradlew clean test

### ISSUE THREAD

**Issue by Anna-64** [Anna-64/diplomproekt1#1]
**Ожидаемый результат:**
./gradlew clean test запускается без ошибок

**Шаги воспроизведения:**
в Docker Desktop 
1) вводим  git clone https://github.com/Anna-64/diplomproekt1

в IDEA 
2) вводим  в терминале: cd gate-simulator;
npm start
3) в новой вкладке IDEA вводим docker-compose up -d --force-recreate
4) в новой вкладке IDEA вводим java -jar aqa-shop.jar
[5) в новой вкладке IDEA вводим ./gradlew clean test]
 после прохождения теста ./gradlew allureServe
далее нажимаем ctrl + C
6) для работы с Postgresql в терминале с командой java -jar aqa-shop.jar нажимаем  ctrl + C
7) в новом терминале IDEA 
java -jar aqa-shop.jar -P:jdbc.url=jdbc:postgresql://localhost:5432/app -P:jdbc.user=app -P:jdbc.password=pass
8) ./gradlew clean test
после прохождения теста ./gradlew allureServe
далее нажимаем ctrl + C

2 Вариант:

**Шаги воспроизведения:**
в Docker Desktop 
1) вводим  git clone https://github.com/Anna-64/diplomproekt1

в IDEA 
2) вводим  в терминале: cd gate-simulator;
npm start
3) в новой вкладке IDEA вводим docker-compose up -d --force-recreate
4) в новой вкладке IDEA вводим java -jar aqa-shop.jar
[5) в новой вкладке IDEA вводим 
./gradlew clean test "-Ddb.url=jdbc:mysql://localhost:3306/app" "-Ddb.user=app" "-Ddb.password=pass"
 после прохождения теста ./gradlew allureServe
далее нажимаем ctrl + C

Все тоже самое, что  и при 1 варианте. Отчеты формируются Gradle, Allure report

PaymentPageTest > ═хтрышфэ√щ ьхё Ў: 00 FAILED
    com.codeborne.selenide.ex.ElementNotFound at PaymentPageTest.java:242
        Caused by: org.openqa.selenium.NoSuchElementException at PaymentPageTest.java:242

PaymentPageTest > ╤Ёюъ юъюэўрэш  фхщёЄтш  ърЁЄ√: Єхъє∙шщ ьхё Ў Єхъє∙хую уюфр, ёЄрЄєё DECLINED FAILED
    com.codeborne.selenide.ex.ElementShould at PaymentPageTest.java:82

48 tests completed, 16 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

**Окружение:**
Windows 10 Домашняя версия
Docker Desktop
Nodejs
IDEA 2022.1
Google Chrome Версия 101.0.4951.67

**Изображение**
![allure report behaviors (дебет)](https://user-images.githubusercontent.com/94541611/171271631-cb754ef0-a4bb-4bae-9878-a58cc143e154.png)
![allure report behaviors (дебет2)](https://user-images.githubusercontent.com/94541611/171271645-e714dc8d-9bfc-4902-90c0-9a18a9363b8e.png)
![allure report behaviors (кредит)](https://user-images.githubusercontent.com/94541611/171271828-48fe26c1-515d-4126-8cb7-9dc95d2259d9.png)
![allure report behaviors (кредит2)](https://user-images.githubusercontent.com/94541611/171271934-0b3dbd9c-6249-45b7-adec-42aa798aa464.png)
![allure report behaviors postgres (дебет)](https://user-images.githubusercontent.com/94541611/171271937-577d6bcd-b3db-4e7c-be54-ad688b3004ef.png)
![allure report behaviors postgres (кредит)](https://user-images.githubusercontent.com/94541611/171272327-9099ec14-eace-40d0-881e-9c130c0a8f8d.png)
![allure report behaviors postgres 2 (кредит)](https://user-images.githubusercontent.com/94541611/171272331-36d5e4dc-8b51-43bc-9f78-20c90229324f.png)
![allure report behaviors postgres 2(дебет)](https://user-images.githubusercontent.com/94541611/171272334-1514340b-2010-40d4-9bee-ac3fbaa10519.png)
![allure report overview postgres](https://user-images.githubusercontent.com/94541611/171272337-657eae77-2d39-43b9-8fed-660040221eb7.png)
![allure report overview](https://user-images.githubusercontent.com/94541611/171272341-f8bf4270-df7c-4055-bd4a-6e8bd1b786b9.png)
![docker-compose](https://user-images.githubusercontent.com/94541611/171272343-a7902ac7-a46f-4856-b048-5f05fcaa9cc3.png)
![gradle mysql](https://user-images.githubusercontent.com/94541611/171272345-a7fdb950-3ba4-40bf-abf4-91fa4dd23d54.png)
![gradle mysql2](https://user-images.githubusercontent.com/94541611/171272346-b7e77f04-278e-4130-bc20-1484bf06b45e.png)
![gradle posgresql](https://user-images.githubusercontent.com/94541611/171272347-83403013-90e6-4ba9-9c31-08537c748af0.png)
![gradle posgresql2](https://user-images.githubusercontent.com/94541611/171272354-1e65fdb7-a0df-46ca-9c25-52e77d74cc9c.png)
![gradlew clean test postgresql](https://user-images.githubusercontent.com/94541611/171272357-2f431c58-4297-4f78-b15d-5fbf850ed37c.png)
![gradlew clean test postgresql2](https://user-images.githubusercontent.com/94541611/171272363-600dfae1-745b-4b12-af2f-ce697c24baeb.png)
![gradlew clean test postgresql3](https://user-images.githubusercontent.com/94541611/171272365-9f5632fd-4b49-49f0-91f6-4455e6188e6a.png)
![gradlew clean test](https://user-images.githubusercontent.com/94541611/171272369-aa496cf5-8724-4d0b-a4e1-d800fddc4202.png)
![gradlew clean test2](https://user-images.githubusercontent.com/94541611/171272372-80608f7d-9752-4057-8279-f9bfcbeaa63a.png)
![gradlew clean test3](https://user-images.githubusercontent.com/94541611/171272373-fb4c4797-b676-49e3-9e0b-9fd62729b252.png)
![gradlew clean test4](https://user-images.githubusercontent.com/94541611/171272374-a57c2d55-8e7b-4175-8e2a-b1093121b251.png)
![jar после прохождения тестов 2](https://user-images.githubusercontent.com/94541611/171272376-6786f81e-8e4a-4623-b04f-4f126019c4e6.png)
![jar после прохождения тестов 3](https://user-images.githubusercontent.com/94541611/171272377-e5a00a14-1007-4da6-a459-495a77da37e0.png)
![jar после прохождения тестов](https://user-images.githubusercontent.com/94541611/171272379-04bc65f0-4507-4333-a2f6-e6104ab4f102.png)
![java jar post error 2](https://user-images.githubusercontent.com/94541611/171272380-95e94be3-a02f-4535-b4af-a8a336def60b.png)
![java jar post error 3](https://user-images.githubusercontent.com/94541611/171272384-b31a3af9-cb67-4da1-bd35-f17a36012ea5.png)
![java jar post error](https://user-images.githubusercontent.com/94541611/171272386-7b638091-b4e5-4bba-b600-14ce3e0877b4.png)
![java jar post](https://user-images.githubusercontent.com/94541611/171272387-2d7f3ce8-545a-46b6-9205-a884e88cf1b3.png)
![java -lar](https://user-images.githubusercontent.com/94541611/171272392-440fbffc-bb43-4748-b3a7-b6d95e54f52e.png)
![npm start](https://user-images.githubusercontent.com/94541611/171272394-1d6bb9c4-da02-48be-bb2c-a0cbec745fe1.png)

**Comment by Anna-64** [comment]
**Вопросы:**
1) когда запускаю п.5 из шаги воспроизведения меня смущает (скриншот: **gradlew clean test**), но отчеты формируются. Страница в браузере открывается, данные автоматические проставляются, ответ формы вижу.

Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details;

CreditPageTest > ─рээ√х ю тырфхы№Ўх ърЁЄ√ єърчрэ√ эхтхЁэю: шь  ш Їрьшыш  эр ъшЁшыышЎх FAILED
    com.codeborne.selenide.ex.ElementNotFound at CreditPageTest.java:173
        Caused by: org.openqa.selenium.NoSuchElementException at CreditPageTest.java:173

2) при остановке выполнении тестов в jar ошибка, увидела уже при остановке (скриншот **jar после прохождения тестов**)

2022-05-31 22:24:56.627 ERROR 7556 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exce
ption [Request processing failed; nested exception is org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request] with root cause

3) В Allure report (скриншот  **в allure report behaviors (дебет)** ) показывает 3 сломанных теста, не могу понять, что я там сделала не так

4) я должна вообще видеть ответ БД во время тестирования?

**Comment by Anna-64** [comment]
Здравствуйте, не могу исправить ошибку на странице 173. Уже все голову сломала. По отчету Allure строка 173 это тест "Данные о владельце карты указаны неверно: имя и фамилия на кириллице" он упал (красным). Что я в тестах прописала не так?

**Comment by Vladanna** [comment]
Добрый день!

Есть у меня предположение что это может быть дефектом в системе. Подскажите если вы руками пробуете пройти этот тест кейс - результат такой же?

**Comment by Anna-64** [comment]
прошла с Debug, прикладываю скрины. А Вы у себя на машине не запускали
![debug1](https://user-images.githubusercontent.com/94541611/171845032-793cf99d-8629-4844-bc8b-3a843384b9de.png)
![debug](https://user-images.githubusercontent.com/94541611/171845038-03d569a8-35d6-45b3-9e3b-2c1a1e9f029a.png)
![debug](https://user-images.githubusercontent.com/94541611/171845043-1cc4ba7a-f757-420c-abee-dfbde5f73be1.png)
![debug1](https://user-images.githubusercontent.com/94541611/171845045-e2129029-f147-4c0e-ab86-c271912c8a97.png)
?
