### ISSUE TITLE
поломонные тесты в allure

### ISSUE THREAD

**Issue by Anna-64** [Anna-64/diplomproekt1#5]
## Ожидаемый результат:
allure отчет без поломанных тестов

## Шаги воспроизведения:
в Docker Desktop

вводим git clone https://github.com/Anna-64/diplomproekt1
в IDEA
2) вводим в терминале: cd gate-simulator;
npm start
3) в новой вкладке IDEA вводим docker-compose up -d --force-recreate
4) в новой вкладке IDEA вводим
java -jar aqa-shop.jar -P:jdbc.url=jdbc:postgres://localhost:5432/app -P:jdbc.user=app -P:jdbc.password=pass
8)в новой вкладке  IDEA вводим  ./gradlew clean test "-Ddb.url=jdbc:postgres://localhost:5432/app" "-Ddb.user=app" "-Ddb.password=pass"
после прохождения теста ./gradlew allureServe
 
Вариант 2
вводим git clone https://github.com/Anna-64/diplomproekt1
в IDEA
2) вводим в терминале: cd gate-simulator;
npm start
3) в новой вкладке IDEA вводим docker-compose up -d --force-recreate
4) в новой вкладке IDEA вводим
java -jar aqa-shop.jar -P:jdbc.url=jdbc:postgres://localhost:5432/app 
8)в новой вкладке  IDEA вводим  ./gradlew clean test "-Ddb.url=jdbc:postgres://localhost:5432/app" "-Ddb.user=app" "-Ddb.password=pass"

## Окружение:
Windows 10 Домашняя версия
Docker Desktop
Nodejs
IDEA 2022.1
![Снимок 2022-06-04 22 47 06](https://user-images.githubusercontent.com/94541611/172021572-b4118f5d-0134-444d-a6e2-36e7882ddcb1.png)

Google Chrome Версия 101.0.4951.67

## Изображение
![Снимок 2022-06-04 22 47 44](https://user-images.githubusercontent.com/94541611/172021563-ca5aec0b-e86b-4c6e-832d-f57d28740e11.png)

![allure postgres 3png](https://user-images.githubusercontent.com/94541611/172021579-b4ed032f-7078-42f0-8ea7-0f0325d0ca87.png)
0000000
![allure postgres](https://user-images.githubusercontent.com/94541611/172021592-3eb47dba-17dd-4e15-90b1-34f0fe6521ea.png)
![allure postgres 1png](https://user-images.githubusercontent.com/94541611/172021769-430b5900-02de-42f3-aaf4-5a743511528d.png)
![allure postgres 2png](https://user-images.githubusercontent.com/94541611/172021802-92ed9550-34ee-4d95-8b39-0ab742745181.png)

![test postgres failed4](https://user-images.githubusercontent.com/94541611/172228482-6ca83f26-6c89-43eb-b67c-c652e3763971.png)
![test postgres failed1](https://user-images.githubusercontent.com/94541611/172228489-561a281e-4c1b-4cef-83f4-3f64a50d24fc.png)
![test postgres failed2](https://user-images.githubusercontent.com/94541611/172228493-582c651b-a358-46c9-aeaa-e1eae83e7521.png)
![test postgres failed3](https://user-images.githubusercontent.com/94541611/172228498-4b52d51e-b10a-4ffd-a619-6db760c8d328.png)

**Comment by Anna-64** [comment]
У меня в Postgresql получается поломанные тесты, так же как и до этого было с тестами mysql.
Но тогда я не передавала параметры для БД. 
Ошибок в тесте я не нашла уже прогоняла их много раз.
Что не так уже не знаю. Помогите, пожалуйста.

**Comment by Vladanna** [comment]
Добрый день! перед запуском в SUT обновите параметры в application.properrties, а именно данные по БД, сейчас у вас там  mysql параметры
так же команда запуска тестов 
`./gradlew clean test "-Ddb.url=jdbc:postgresql://localhost:5432/app" "-Ddb.user=app" "-Ddb.password=pass" ` избыточная, вы и  user и  pass передаете уже в build.gradle
если и это не сработает укажите явно значения внутри метода подключения к БД в тестах
